var dir_520a649ed2b1c3b658a695aeefe46a5a =
[
    [ "Classifier.cc", "Classifier_8cc_source.html", null ],
    [ "Classifier.h", "Classifier_8h_source.html", null ],
    [ "KDB.cc", "KDB_8cc_source.html", null ],
    [ "KDB.h", "KDB_8h_source.html", null ],
    [ "KDBLd.cc", "KDBLd_8cc_source.html", null ],
    [ "KDBLd.h", "KDBLd_8h_source.html", null ],
    [ "Proposal.cc", "Proposal_8cc_source.html", null ],
    [ "Proposal.h", "Proposal_8h_source.html", null ],
    [ "SPnDE.cc", "SPnDE_8cc_source.html", null ],
    [ "SPnDE.h", "SPnDE_8h_source.html", null ],
    [ "SPODE.cc", "SPODE_8cc_source.html", null ],
    [ "SPODE.h", "SPODE_8h_source.html", null ],
    [ "SPODELd.cc", "SPODELd_8cc_source.html", null ],
    [ "SPODELd.h", "SPODELd_8h_source.html", null ],
    [ "TAN.cc", "TAN_8cc_source.html", null ],
    [ "TAN.h", "TAN_8h_source.html", null ],
    [ "TANLd.cc", "TANLd_8cc_source.html", null ],
    [ "TANLd.h", "TANLd_8h_source.html", null ],
    [ "XSP2DE.cc", "XSP2DE_8cc_source.html", null ],
    [ "XSP2DE.h", "XSP2DE_8h_source.html", null ],
    [ "XSPODE.cc", "XSPODE_8cc_source.html", null ],
    [ "XSPODE.h", "XSPODE_8h_source.html", null ]
];